### ISSUE TITLE
Add checksum for redis-stable

### ISSUE THREAD

**Issue by mohae** [redis/redis-hashes#1]
Adding the checksum for the current redis-stable release would be helpful for two reasons:
- be able to check the checksum of the downloaded redis-stable tarball.
- being able to configure automated deployment setups to check the hash of the downloaded tarball when specifying redis-stable instead of a specific point release.

Thanks for considering.

**Comment by badboy** [comment]
redis-stable is always the latest point release, so you could check against the last line of the hashes file (stripping the filename of course)

**Comment by mohae** [comment]
I had expected that, but I get 8ad74084113c78faa97c47e7dac195f4b3991e1e as the current checksum for redis-stable.tar.gz.

This was the value from both salt and doing a `sha1sum` on the file from the command-line. I'm probably misunderstanding something here.

**Comment by badboy** [comment]
Ah, sorry, you're actually right. The `redis-stable.tar.gz` has a folder `redis-stable` to make it easy to work with in scripts (no need to guess or glob the extracted directory), therefore the checksum is different.

So it's up to @antirez to decide if he does that.
As a workaround it's possible to go the other way round: Fetch the hashes file and extract the URL, which is included.

**Comment by CVTJNII** [comment]
+1 for this.  As the stable tarball is distributed insecurely we need a checksum of it.

**Comment by marcobellaccini** [comment]
+1 from me, too...
In the meanwhile, I implemented @badboy  's workaround:
[https://gist.github.com/marcobellaccini/1655cfe7e6fd8eeecac8352ca972aad3](https://gist.github.com/marcobellaccini/1655cfe7e6fd8eeecac8352ca972aad3)

**Comment by jpickwell** [comment]
You can use the following file link for redis-stable: http://download.redis.io/redis-stable.tar.gz.SHA256SUM

**Comment by marcobellaccini** [comment]
Thank you.
Anyway, now that the tarballs are served over HTTPS, this whole issue is far less important.

**Comment by itamarhaber** [comment]
Woot - an issue that can be closed :)

Yep, we've recently enabled HTTPS so anyone can move to using that. The HTTP was kept to avoid world-breakage and the sha sum file was added for parties interested in verifying the download.
